 let jobs=[
    {
      "title": "Data Analyst - Clinical Data Management",
      "companyName": "Cognizant",
      "ratings": 3.4,
      "reviews": "77.7k",
      "years": "3-5",
      "opening": "Not disclosed",
      "location": "Cumilla",
      "shift": "Day 10 hours",
      "keywords": [
        "Clinical Data Management",
        "Medidata Rave",
        "RaveCdm",
        "Clinical Data",
        "Data management",
        "Data analysis",
        "Management"
      ],
      "time": "7 days ago",
      "logo": "https://img.naukimg.com/logo_images/groups/v1/4156.gif",
      "job_Summary": "Seeking a Process Specialist-CDM with minimum 3.5 years of experience in Clinical operations.",
      "roles_Responsibilities": "Responsible for managing and overseeing clinical data management, ensuring accuracy and compliance.",
      "role": "Healthcare & Life Sciences - Other",
      "industry_type": "IT Services & Consulting",
      "department": "Healthcare & Life Sciences",
      "employment_Type": "Full Time, Permanent",
      "education": "B.Pharma in Any Specialization, B.Sc in Any Specialization",
      "key_Skills": "Clinical Data Management"
    },
    {
      "title": "Clinical Data Manager",
      "companyName": "Accenture",
      "ratings": 4.2,
      "reviews": "89.1k",
      "years": "5-7",
      "opening": "Not disclosed",
      "location": "Dhaka",
      "shift": "Day 8 hours",
      "keywords": [
        "Data analysis",
        "Clinical Data Management",
        "Medidata Rave",
        "Clinical operations",
        "Regulatory compliance"
      ],
      "time": "3 days ago",
      "logo": "https://img.naukimg.com/logo_images/groups/v1/4897.gif",
      "job_Summary": "Seeking an experienced Clinical Data Manager with a strong background in regulatory data analysis.",
      "roles_Responsibilities": "Analyze and manage clinical data, ensuring it meets regulatory standards.",
      "role": "Healthcare Data Analyst",
      "industry_type": "IT Services & Consulting",
      "department": "Healthcare",
      "employment_Type": "Full Time, Contract",
      "education": "M.Sc in Clinical Research, B.Sc in Any Specialization",
      "key_Skills": "Clinical Data Management, Regulatory Compliance"
    },
    {
      "title": "Senior Data Analyst - Healthcare",
      "companyName": "TCS",
      "ratings": 4.0,
      "reviews": "102.5k",
      "years": "6-8",
      "opening": "5",
      "location": "Sylhet",
      "shift": "Night 12 hours",
      "keywords": [
        "Data analysis",
        "Clinical Research",
        "Data interpretation",
        "Medidata Rave",
        "Management"
      ],
      "time": "14 days ago",
      "logo": "https://img.naukimg.com/logo_images/groups/v1/4156.gif",
      "job_Summary": "Seeking a Senior Data Analyst to lead clinical research projects with expertise in Medidata Rave.",
      "roles_Responsibilities": "Lead clinical data projects, ensuring accuracy and developing data strategies.",
      "role": "Clinical Data Analyst",
      "industry_type": "Healthcare",
      "department": "Data Management",
      "employment_Type": "Full Time, Permanent",
      "education": "M.Pharma in Any Specialization",
      "key_Skills": "Clinical Data, Data Analysis"
    },
    {
      "title": "Associate Clinical Data Specialist",
      "companyName": "Infosys",
      "ratings": 3.9,
      "reviews": "90.5k",
      "years": "2-4",
      "opening": "10",
      "location": "Chittagong",
      "shift": "Day 9 hours",
      "keywords": [
        "Clinical Data Management",
        "Data Cleaning",
        "Medidata Rave",
        "Clinical Operations"
      ],
      "time": "9 days ago",
      "logo": "https://img.naukimg.com/logo_images/groups/v1/3845.gif",
      "job_Summary": "Seeking an Associate Clinical Data Specialist with expertise in Medidata Rave for data cleaning.",
      "roles_Responsibilities": "Manage clinical data, ensuring it is properly cleaned and validated.",
      "role": "Clinical Data Specialist",
      "industry_type": "IT Consulting",
      "department": "Healthcare & Data Management",
      "employment_Type": "Full Time, Permanent",
      "education": "B.Sc in Any Specialization",
      "key_Skills": "Medidata Rave, Clinical Data"
    },
    {
      "title": "Data Scientist - Clinical Research",
      "companyName": "IBM",
      "ratings": 4.5,
      "reviews": "55.7k",
      "years": "3-6",
      "opening": "Not disclosed",
      "location": "Barisal",
      "shift": "Day 8 hours",
      "keywords": [
        "Data Science",
        "Clinical Research",
        "Medidata Rave",
        "Clinical Data",
        "Management"
      ],
      "time": "5 days ago",
      "logo": "https://img.naukimg.com/logo_images/groups/v1/4156.gif",
      "job_Summary": "Data Scientist needed to drive clinical research data projects, focusing on data science applications.",
      "roles_Responsibilities": "Develop data science models for clinical research, analyzing large datasets.",
      "role": "Healthcare Data Scientist",
      "industry_type": "IT Services",
      "department": "Healthcare",
      "employment_Type": "Full Time, Permanent",
      "education": "M.Sc in Data Science",
      "key_Skills": "Data Science, Medidata Rave"
    },
    {
      "title": "Data Manager - Clinical Trials",
      "companyName": "Medtronic",
      "ratings": 4.1,
      "reviews": "34.9k",
      "years": "5-8",
      "opening": "1",
      "location": "Dhaka",
      "shift": "Flexible hours",
      "keywords": [
        "Clinical Data Management",
        "Clinical Trials",
        "Data management",
        "Research & Development"
      ],
      "time": "2 days ago",
      "logo": "https://img.naukimg.com/logo_images/groups/v1/6123.gif",
      "job_Summary": "Manage clinical trials data and oversee the quality of data for global clinical studies.",
      "roles_Responsibilities": "Manage the collection and reporting of clinical trial data for global studies.",
      "role": "Data Manager",
      "industry_type": "Healthcare",
      "department": "Clinical Research",
      "employment_Type": "Full Time, Contract",
      "education": "M.Pharma, B.Sc in Any Specialization",
      "key_Skills": "Clinical Trials, Data Management"
    },
    {
      "title": "Clinical Data Coordinator",
      "companyName": "Pfizer",
      "ratings": 4.8,
      "reviews": "12.1k",
      "years": "1-3",
      "opening": "2",
      "location": "Rajshahi",
      "shift": "Day 9 hours",
      "keywords": [
        "Clinical Data Management",
        "Data collection",
        "Regulatory compliance",
        "Medidata Rave"
      ],
      "time": "3 days ago",
      "logo": "https://img.naukimg.com/logo_images/groups/v1/5552.gif",
      "job_Summary": "Seeking a Clinical Data Coordinator to assist in data collection and regulatory compliance.",
      "roles_Responsibilities": "Assist in collecting and managing clinical data for drug trials.",
      "role": "Clinical Data Coordinator",
      "industry_type": "Pharmaceutical",
      "department": "Clinical Research",
      "employment_Type": "Full Time, Permanent",
      "education": "B.Sc in Any Specialization",
      "key_Skills": "Data Collection, Medidata Rave"
    },
    {
      "title": "Clinical Research Analyst",
      "companyName": "Roche",
      "ratings": 4.6,
      "reviews": "44.1k",
      "years": "3-5",
      "opening": "3",
      "location": "Dhaka",
      "shift": "Flexible hours",
      "keywords": [
        "Clinical Data Management",
        "Clinical Research",
        "Data interpretation",
        "Medidata Rave"
      ],
      "time": "10 days ago",
      "logo": "https://img.naukimg.com/logo_images/groups/v1/5156.gif",
      "job_Summary": "Seeking a Clinical Research Analyst to manage and analyze clinical research data.",
      "roles_Responsibilities": "Analyze clinical research data and ensure regulatory compliance.",
      "role": "Clinical Data Analyst",
      "industry_type": "Pharmaceutical",
      "department": "Clinical Research",
      "employment_Type": "Full Time, Contract",
      "education": "B.Sc in Clinical Research",
      "key_Skills": "Data Management, Medidata Rave"
    },
    {
      "title": "Data Manager - Research & Development",
      "companyName": "Novartis",
      "ratings": 4.3,
      "reviews": "66.4k",
      "years": "6-9",
      "opening": "Not disclosed",
      "location": "Khulna",
      "shift": "Day 8 hours",
      "keywords": [
        "Clinical Data Management",
        "R&D",
        "Medidata Rave",
        "Clinical Trials",
        "Management"
      ],
      "time": "11 days ago",
      "logo": "https://img.naukimg.com/logo_images/groups/v1/4995.gif",
      "job_Summary": "Lead data management for R&D projects focusing on clinical trials.",
      "roles_Responsibilities": "Oversee clinical data for R&D projects, ensuring data integrity.",
      "role": "R&D Data Manager",
      "industry_type": "Pharmaceutical",
      "department": "Clinical Research & Development",
      "employment_Type": "Full Time, Permanent",
      "education": "M.Pharma, B.Pharma",
      "key_Skills": "Clinical Data Management, R&D"
    },
    {
      "title": "Data Specialist - Life Sciences",
      "companyName": "Sanofi",
      "ratings": 4.7,
      "reviews": "54.9k",
      "years": "4-6",
      "opening": "1",
      "location": "Barisal",
      "shift": "Day 10 hours",
      "keywords": [
        "Clinical Data Management",
        "Data analysis",
        "Medidata Rave",
        "Clinical Research"
      ],
      "time": "8 days ago",
      "logo": "https://img.naukimg.com/logo_images/groups/v1/5235.gif",
      "job_Summary": "Clinical Data Specialist with a focus on data analysis and research management.",
      "roles_Responsibilities": "Analyze clinical data and contribute to research management.",
      "role": "Data Specialist",
      "industry_type": "Pharmaceutical",
      "department": "Clinical Research",
      "employment_Type": "Full Time, Permanent",
      "education": "B.Sc in Life Sciences",
      "key_Skills": "Clinical Data, Medidata Rave"
    }
  ]
  
  module.exports = jobs;